objects/Artifact__c.object
<CustomObject>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The org credential where the metadata of the Artifact is going to be retrieved from, for unlocked packages and 2GP.
The org credential where the unmanaged package is created from.</inlineHelpText>
        <label>Source Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Artifacts</relationshipLabel>
        <relationshipName>Artifacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Package</label>
    <nameField>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Copado_Notification__c.object
<CustomObject>
    <description>Used for Copado Notifications using the Streaming API.</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Copado Notification</label>
    <nameField>
        <label>CopadoNotification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Copado Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deployment_Flow__c.object
<CustomObject>
    <fields>
        <fullName>Git_Repository__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>Git_Repository__c</referenceTo>
        <relationshipName>Deployment_Flows</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Environment__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Production/Developer</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch Org</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Git_Backup__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <description>Branch of the selected Git Repository (e.g. master). Snapshots and Commits done in the Git Snapshot will affect the specified branch.</description>
        <inlineHelpText>Git branch related to the Org. Be aware that branch names are case sensitive.</inlineHelpText>
        <label>Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Git_Repository__c</fullName>
        <description>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>Git_Repository__c</referenceTo>
        <relationshipLabel>Git Snapshots</relationshipLabel>
        <relationshipName>Git_Backups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <description>A validated Org Credential used to retrieve the metadata that will be committed to the specified Branch in the Git Snapshot.</description>
        <inlineHelpText>A validated Org Credential used to retrieve the metadata that will be committed to the specified Branch in the Git Snapshot.</inlineHelpText>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Git Snapshots</relationshipLabel>
        <relationshipName>Git_Backups</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Git Snapshot</label>
    <nameField>
        <label>Git Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <fields>
        <fullName>Developer_Hub_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Developer Hub Org</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Org__c.is_Developer_Hub_Org__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Org Credentials</relationshipLabel>
        <relationshipName>Org_Credentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</description>
        <inlineHelpText>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Org Credentials</relationshipLabel>
        <relationshipName>Org_Credentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>is_Developer_Hub_Org__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Developer Hub Org</label>
        <type>Checkbox</type>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <fields>
        <fullName>Deployment_Flow__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If working with Copado Change Management, the Project must be linked to a Pipeline.</inlineHelpText>
        <label>Pipeline</label>
        <referenceTo>Deployment_Flow__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Test_Run__c.object
<CustomObject>
    <description>The execution of the test script.</description>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Test Runs</relationshipLabel>
        <relationshipName>Test_Runs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Test_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Test_Script__c</fullName>
        <label>Test Script</label>
        <referenceTo>Test_Script__c</referenceTo>
        <relationshipName>Test_Executions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipName>Test_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Run</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Test Run Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Runs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Test_Script__c.object
<CustomObject>
    <description>The template test script.</description>
    <fields>
        <fullName>Org__c</fullName>
        <label>Org</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>User_Story__r.Project__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipLabel>Test Scripts (User Story)</relationshipLabel>
        <relationshipName>Test_Scripts_UserStory</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{00000}</displayFormat>
        <label>Test Script Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</description>
        <inlineHelpText>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</description>
        <inlineHelpText>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</inlineHelpText>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>User Stories (Org Credential)</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project where the User Story belongs.</description>
        <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Story_Title__c</fullName>
        <description>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</description>
        <inlineHelpText>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</inlineHelpText>
        <label>User Story Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestCreateUSScratchOrg.cls
@IsTest
private class  TestCreateUSScratchOrg {
    private static final String jsonfile = '{"features":["Communities","ServiceCloud","Chatbot"],"settings":{"orgPreferenceSettings":{"networksEnabled":true,"s1DesktopEnabled":true,"s1EncryptedStoragePref2":false},"omniChannelSettings":{"enableOmniChannel":true},"caseSettings":{"systemUserEmail":"support@acme.com"}}}';
    private static final String orgDefinitionfile = '{"orgName":"Acme","edition":"Enterprise","features":["Communities","ServiceCloud","Chatbot"],"settings":{"orgPreferenceSettings":{"networksEnabled":true,"s1DesktopEnabled":true,"s1EncryptedStoragePref2":false},"omniChannelSettings":{"enableOmniChannel":true},"caseSettings":{"systemUserEmail":"support@acme.com"}}}';

    @TestSetup static void setup() {
        // Create common test records
        insert TestUtilities.getTestSettings();
        TestUtilities.assignLicense(UserInfo.getUserName(), true, true, true, true, true);
        TestUtilities.createAllDXTestData();
    }

    @IsTest static void createUserStoryScratchOrg(){
        //Use the PageReference Apex class to instantiate a page
        PageReference pageRef = Page.CreateUserStoryScratchOrg;

        //In this case, the Visualforce page named 'DXOperation' is the starting point of this test method.
        Test.setCurrentPage(pageRef);
        List<String> orgNameStrings = new List<String>{'Dev Hub 1','Scratch Org Branch'};
        String devHub;
        List<Org__c> orgList = [SELECT Id, Name, Developer_Hub_Org__c, is_Developer_Hub_Org__c FROM Org__c WHERE Name = :orgNameStrings];
        for(Org__c orgCred : orgList){
            if(orgCred.is_Developer_Hub_Org__c){
                devHub = orgCred.Id;
                break;
            }
        }
        for(Org__c orgCred : orgList){
            if(!orgCred.is_Developer_Hub_Org__c){
                orgCred.Developer_Hub_Org__c = devHub;
                break;
            }
        }
        update orgList;

        User_Story__c us = [SELECT Id,Name, Org_Credential__c FROM User_Story__c WHERE User_Story_Title__c =: 'Error on dx operation 2'];
        pageRef.getParameters().put('Id', us.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(us);

        //Create test run
        Test_Script__c testScript = new Test_Script__c();
        testScript.User_Story__c = us.Id;
        insert testScript;

        Test_Run__c testRun = new Test_Run__c();
        testRun.User_Story__c = us.Id;
        testRun.Test_Script__c = testScript.Id;
        insert testRun;

        Test_Run__c testRunObject = [SELECT Id, Name, Test_Script__r.User_Story__r.Project__r.Deployment_Flow__r.Git_Repository__c, Test_Script__r.User_Story__r.Project__r.Deployment_Flow__c, Test_Script__r.User_Story__r.Project__c, Test_Script__r.User_Story__r.Org_Credential__c, Test_Script__r.User_Story__r.Org_Credential__r.Developer_Hub_Org__c FROM Test_Run__c WHERE Id = :testRun.Id LIMIT 1];
        Attachment att = new Attachment();
        att.ParentId = testRunObject.Test_Script__r.User_Story__r.Org_Credential__c;
        att.Name = SfdxAPIHelper.DX_DEFINITION_FILE;
        att.Body = Blob.valueOf(orgDefinitionfile);
        insert  att;

        //Instantiate and construct the controller class of DX Operation page.
        CreateUserStoryScratchOrgController controller = new CreateUserStoryScratchOrgController(sc);

        controller.getChildComponentController();

        //Instantiate and construct the controller class of component.
        ScratchOrgMetadataController somcController = new ScratchOrgMetadataController();
        somcController.setComponentMode('wizard');
        somcController.setShowTemplateButtons(false);
        somcController.setShowButtons(true);
        somcController.setPageController(controller);
        somcController.setControllerKey('ScratchOrgMetadata');
        somcController.typeName = 'branch';
        //somcController.showPatchOptions = false;

        controller.nextStep(); // it will return because dev hub org id is not selected
        controller.previousStep();
        controller.nextStep();

        ScratchOrgController socController = new ScratchOrgController();
        socController.setComponentMode('wizard');
        socController.setShowTemplateButtons(false);
        socController.setShowButtons(true);
        socController.setPageController(controller);
        socController.setControllerKey('ScratchOrgTemplate');

        socController.orgTemplate.setOrgName('FO test');

        //Org__c devHubOrg = [SELECT Id FROM Org__c WHERE Name =: 'Dev Hub 1'];
        socController.setDevHubOrgId(devHub);

        //Select git repository and populate grid panel
        Git_Repository__c gr = [SELECT Id, Name FROM Git_Repository__c WHERE Name =: 'git 1'];
        //somcController.repoId = gr.Id;
        //somcController.repoName = gr.Name;
        // TODO wrapper class will be updating the records

        //Select git snapshot from grid panel and populate branch name parameter at dxoperation controller
        Git_Backup__c gb = [SELECT Id, Branch__c FROM Git_Backup__c WHERE Git_Repository__c =: gr.Id];

        //Select branch and render artifact panels
        ApexPages.currentPage().getParameters().put('nextStepParam', gb.Branch__c);
        controller.setJsonSettingsFeatures(jsonfile);

        controller.nextStep();
        System.assertEquals('COMPLETE',controller.definition);
        controller.previousStep();
        controller.nextStep();

        ScratchOrgExtensionsController soecController = new ScratchOrgExtensionsController();
        soecController.setComponentMode('wizard');
        soecController.setShowTemplateButtons(false);
        soecController.setShowButtons(true);
        soecController.setPageController(controller);
        soecController.setControllerKey('ScratchOrgExtensions');
        soecController.sourceOrgId = devHub;
        soecController.populateDeployments();
        //soecController.selectedDeploymentId = [SELECT Id FROM Deployment__c WHERE Name = 'Dev1 Deployment' LIMIT 1].Id;
        soecController.addToExtensions();

        controller.nextStep();
        controller.previousStep();
        controller.nextStep();

        ScratchOrgCompletionController soccController = new ScratchOrgCompletionController();
        soccController.setComponentMode('wizard');
        soccController.setShowTemplateButtons(false);
        soccController.setShowButtons(true);
        soccController.setPageController(controller);
        soccController.setControllerKey('ScratchOrgCompletion');
        soccController.tRun = testRunObject;

        Test.startTest();
        MockHttpResponseGenerator fullScratchOrgFakeResponse = new MockHttpResponseGenerator(200,'Complete','{"example":"test"}',null);
        Test.setMock(HttpCalloutMock.class, fullScratchOrgFakeResponse);

        soccController.createFullScratchOrg();

        ApexPages.currentPage().getParameters().put('csvPerm', '');
        //soccController.getSelectedPermissionSets();

        MockHttpResponseGenerator fakeResponse = new MockHttpResponseGenerator(200,'Complete','{"example":"test"}',null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        controller.nextStep();

        controller.loadReviewData();
        //run the event listener job for create org job
        ApexPages.currentPage().getParameters().put('jobFinished', 'true');
        ApexPages.currentPage().getParameters().put('jobSuccess', 'true');
        ApexPages.currentPage().getParameters().put('jobMessage', '');
        ApexPages.currentPage().getParameters().put('jobType', CopadoNotificationHelper.DX_CREATE_FULL_ORG);
        controller.jobStatusNotification();

        soccController.showDeploymentFlow = true;
        soccController.deploymentFlowOperations();
        controller.nextStepOrgTemplate();
        controller.fullCreateCompleted();

        Test.stopTest();
    }

    @IsTest static void createUserStoryScratchOrgUnlockedPackage(){
        //Use the PageReference Apex class to instantiate a page
        PageReference pageRef = Page.CreateUserStoryScratchOrg;

        //In this case, the Visualforce page named 'DXOperation' is the starting point of this test method.
        Test.setCurrentPage(pageRef);

        User_Story__c us = [SELECT Id,Name, Org_Credential__c FROM User_Story__c WHERE User_Story_Title__c =: 'Error on dx operation 2'];
        pageRef.getParameters().put('Id', us.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(us);

        //Instantiate and construct the controller class of DX Operation page.
        CreateUserStoryScratchOrgController controller = new CreateUserStoryScratchOrgController(sc);

        controller.getChildComponentController();

        //Instantiate and construct the controller class of component.
        ScratchOrgMetadataController somcController = new ScratchOrgMetadataController();
        somcController.setComponentMode('wizard');
        somcController.setShowTemplateButtons(false);
        somcController.setShowButtons(true);
        somcController.setPageController(controller);
        somcController.setControllerKey('ScratchOrgMetadata');
        somcController.typeName = 'unlocked'; //Old value "unlockPackage"
        //somcController.showPatchOptions = false;

        controller.nextStep(); // it will return because dev hub org id is not selected
        controller.previousStep();
        controller.nextStep();//

        ScratchOrgController socController = new ScratchOrgController();
        socController.setComponentMode('wizard');
        socController.setShowTemplateButtons(false);
        socController.setShowButtons(true);
        socController.setPageController(controller);
        socController.setControllerKey('ScratchOrgTemplate');

        socController.orgTemplate.setOrgName('FO test');

        //socController.mergeArtifactOrgDefinitionDependencies();

        Org__c devHubOrg = [SELECT Id FROM Org__c WHERE Name =: 'Dev Hub 1'];
        socController.setDevHubOrgId(devHubOrg.Id);

        //Select git repository and populate grid panel
        Git_Repository__c gr = [SELECT Id, Name FROM Git_Repository__c WHERE Name =: 'git 1'];
        //somcController.repoId = gr.Id;
        //somcController.repoName = gr.Name;
        // TODO wrapper class will be updating the records

        //Select git snapshot from grid panel and populate branch name parameter at dxoperation controller
        Git_Backup__c gb = [SELECT Id, Branch__c FROM Git_Backup__c WHERE Git_Repository__c =: gr.Id];

        //Select branch and render artifact panels
        ApexPages.currentPage().getParameters().put('nextStepParam', gb.Branch__c);
        controller.setJsonSettingsFeatures(jsonfile);

        controller.nextStep();
        System.assertEquals('COMPLETE',controller.definition);
        controller.previousStep();
        controller.nextStep();

        ScratchOrgExtensionsController soecController = new ScratchOrgExtensionsController();
        soecController.setComponentMode('wizard');
        soecController.setShowTemplateButtons(false);
        soecController.setShowButtons(true);
        soecController.setPageController(controller);
        soecController.setControllerKey('ScratchOrgExtensions');

        controller.nextStep();
        controller.previousStep();
        controller.nextStep();

        ScratchOrgCompletionController soccController = new ScratchOrgCompletionController();
        soccController.setComponentMode('wizard');
        soccController.setShowTemplateButtons(false);
        soccController.setShowButtons(true);
        soccController.setPageController(controller);
        soccController.setControllerKey('ScratchOrgCompletion');

        soccController.createFullScratchOrg();

        ApexPages.currentPage().getParameters().put('csvPerm', '');
        //soccController.getSelectedPermissionSets();

        Test.startTest();
        MockHttpResponseGenerator fakeResponse = new MockHttpResponseGenerator(200,'Complete','{"example":"test"}',null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        controller.nextStep();

        controller.loadReviewData();
        //run the event listener job for create org job
        ApexPages.currentPage().getParameters().put('jobFinished', 'true');
        ApexPages.currentPage().getParameters().put('jobSuccess', 'true');
        ApexPages.currentPage().getParameters().put('jobMessage', '');
        ApexPages.currentPage().getParameters().put('jobType', CopadoNotificationHelper.DX_CREATE_FULL_ORG);
        controller.jobStatusNotification();

        soccController.showDeploymentFlow = true;
        soccController.deploymentFlowOperations();

        Test.stopTest();
    }

    @IsTest static void createUserStoryScratchOrgArtifact(){
        //Use the PageReference Apex class to instantiate a page
        PageReference pageRef = Page.CreateUserStoryScratchOrg;

        //In this case, the Visualforce page named 'DXOperation' is the starting point of this test method.
        Test.setCurrentPage(pageRef);

        User_Story__c us = [SELECT Id,Name, Org_Credential__c FROM User_Story__c WHERE User_Story_Title__c =: 'Error on dx operation 2'];
        Artifact__c at = [SELECT Id FROM Artifact__c WHERE Name = 'StaticResources2' LIMIT 1];

        pageRef.getParameters().put('Id', us.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(us);

        //Instantiate and construct the controller class of DX Operation page.
        CreateUserStoryScratchOrgController controller = new CreateUserStoryScratchOrgController(sc);

        controller.getChildComponentController();

        //Instantiate and construct the controller class of component.
        ScratchOrgMetadataController somcController = new ScratchOrgMetadataController();
        somcController.setComponentMode('wizard');
        somcController.setShowTemplateButtons(false);
        somcController.setShowButtons(true);
        somcController.setPageController(controller);
        somcController.setControllerKey('ScratchOrgMetadata');
        somcController.typeName = 'artifact';

        somcController.setSourceSelections(at.Id);

        controller.nextStep(); // it will return because dev hub org id is not selected
        controller.previousStep();
        controller.nextStep();//

        ScratchOrgController socController = new ScratchOrgController();
        socController.setComponentMode('wizard');
        socController.setShowTemplateButtons(false);
        socController.setShowButtons(true);
        socController.setPageController(controller);
        socController.setControllerKey('ScratchOrgTemplate');
        ScratchOrgDefinition orgTemplate = socController.orgTemplate;

        Attachment orgDefinitionDependency = new Attachment();
        orgDefinitionDependency.ParentId = at.Id;
        orgDefinitionDependency.Body = Blob.valueOf(jsonfile);
        orgDefinitionDependency.Name = SfdxAPIHelper.DX_DEFINITION_FILE;
        insert orgDefinitionDependency;

        //socController.mergeArtifactOrgDefinitionDependencies();
        socController.orgTemplate.setOrgName('FO test');

        Org__c devHubOrg = [SELECT Id FROM Org__c WHERE Name =: 'Dev Hub 1'];
        socController.setDevHubOrgId(devHubOrg.Id);

        //Select git repository and populate grid panel
        Git_Repository__c gr = [SELECT Id, Name FROM Git_Repository__c WHERE Name =: 'git 1'];
        //somcController.repoId = gr.Id;
        //somcController.repoName = gr.Name;
        // TODO wrapper class will be updating the records

        //Select git snapshot from grid panel and populate branch name parameter at dxoperation controller
        Git_Backup__c gb = [SELECT Id, Branch__c FROM Git_Backup__c WHERE Git_Repository__c =: gr.Id];

        //Select branch and render artifact panels
        ApexPages.currentPage().getParameters().put('nextStepParam', gb.Branch__c);
        controller.setJsonSettingsFeatures(jsonfile);

        controller.nextStep();
        System.assertEquals('COMPLETE',controller.definition);
        controller.previousStep();
        controller.nextStep();

        ScratchOrgExtensionsController soecController = new ScratchOrgExtensionsController();
        soecController.setComponentMode('wizard');
        soecController.setShowTemplateButtons(false);
        soecController.setShowButtons(true);
        soecController.setPageController(controller);
        soecController.setControllerKey('ScratchOrgExtensions');

        controller.nextStep();
        controller.previousStep();
        controller.nextStep();

        ScratchOrgCompletionController soccController = new ScratchOrgCompletionController();
        soccController.setComponentMode('wizard');
        soccController.setShowTemplateButtons(false);
        soccController.setShowButtons(true);
        soccController.setPageController(controller);
        soccController.setControllerKey('ScratchOrgCompletion');

        soccController.createFullScratchOrg();

        ApexPages.currentPage().getParameters().put('csvPerm', '');
        //soccController.getSelectedPermissionSets();

        Test.startTest();
        MockHttpResponseGenerator fakeResponse = new MockHttpResponseGenerator(200,'Complete','{"example":"test"}',null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        controller.nextStep();

        controller.loadReviewData();
        //run the event listener job for create org job
        ApexPages.currentPage().getParameters().put('jobFinished', 'true');
        ApexPages.currentPage().getParameters().put('jobSuccess', 'true');
        ApexPages.currentPage().getParameters().put('jobMessage', '');
        ApexPages.currentPage().getParameters().put('jobType', CopadoNotificationHelper.DX_CREATE_FULL_ORG);
        controller.jobStatusNotification();

        soccController.showDeploymentFlow = true;
        soccController.deploymentFlowOperations();

        Test.stopTest();
    }

    @IsTest static void createUserStoryScratchOrgPatch(){
        //Use the PageReference Apex class to instantiate a page
        PageReference pageRef = Page.CreateUserStoryScratchOrg;

        //In this case, the Visualforce page named 'DXOperation' is the starting point of this test method.
        Test.setCurrentPage(pageRef);

        User_Story__c us = [SELECT Id,Name, Org_Credential__c FROM User_Story__c WHERE User_Story_Title__c =: 'Error on dx operation 2'];
        pageRef.getParameters().put('Id', us.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(us);

        //Instantiate and construct the controller class of DX Operation page.
        CreateUserStoryScratchOrgController controller = new CreateUserStoryScratchOrgController(sc);

        controller.getChildComponentController();

        //Instantiate and construct the controller class of component.
        ScratchOrgMetadataController somcController = new ScratchOrgMetadataController();
        somcController.setComponentMode('wizard');
        somcController.setShowTemplateButtons(false);
        somcController.setShowButtons(true);
        somcController.setPageController(controller);
        somcController.setControllerKey('ScratchOrgMetadata');
        somcController.typeName = 'patch';

        controller.nextStep(); // it will return because dev hub org id is not selected
        controller.previousStep();
        controller.nextStep();//

        ScratchOrgController socController = new ScratchOrgController();
        socController.setComponentMode('wizard');
        socController.setShowTemplateButtons(false);
        socController.setShowButtons(true);
        socController.setPageController(controller);
        socController.setControllerKey('ScratchOrgTemplate');

        socController.orgTemplate.setOrgName('FO test');

        Org__c devHubOrg = [SELECT Id FROM Org__c WHERE Name =: 'Dev Hub 1'];
        socController.setDevHubOrgId(devHubOrg.Id);

        //Select git repository and populate grid panel
        Git_Repository__c gr = [SELECT Id, Name FROM Git_Repository__c WHERE Name =: 'git 1'];
        //somcController.repoId = gr.Id;
        //somcController.repoName = gr.Name;
        // TODO wrapper class will be updating the records

        //Select git snapshot from grid panel and populate branch name parameter at dxoperation controller
        Git_Backup__c gb = [SELECT Id, Branch__c FROM Git_Backup__c WHERE Git_Repository__c =: gr.Id];

        //Select branch and render artifact panels
        ApexPages.currentPage().getParameters().put('nextStepParam', gb.Branch__c);
        controller.setJsonSettingsFeatures(jsonfile);

        controller.nextStep();
        System.assertEquals('COMPLETE',controller.definition);
        controller.previousStep();
        controller.nextStep();

        ScratchOrgExtensionsController soecController = new ScratchOrgExtensionsController();
        soecController.setComponentMode('wizard');
        soecController.setShowTemplateButtons(false);
        soecController.setShowButtons(true);
        soecController.setPageController(controller);
        soecController.setControllerKey('ScratchOrgExtensions');

        controller.nextStep();
        controller.previousStep();
        controller.nextStep();

        ScratchOrgCompletionController soccController = new ScratchOrgCompletionController();
        soccController.setComponentMode('wizard');
        soccController.setShowTemplateButtons(false);
        soccController.setShowButtons(true);
        soccController.setPageController(controller);
        soccController.setControllerKey('ScratchOrgCompletion');

        soccController.createFullScratchOrg();

        ApexPages.currentPage().getParameters().put('csvPerm', '');
        //soccController.getSelectedPermissionSets();

        Test.startTest();
        MockHttpResponseGenerator fakeResponse = new MockHttpResponseGenerator(200,'Complete','{"example":"test"}',null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        controller.nextStep();

        controller.loadReviewData();
        //run the event listener job for create org job
        ApexPages.currentPage().getParameters().put('jobFinished', 'true');
        ApexPages.currentPage().getParameters().put('jobSuccess', 'true');
        ApexPages.currentPage().getParameters().put('jobMessage', '');
        ApexPages.currentPage().getParameters().put('jobType', CopadoNotificationHelper.DX_CREATE_FULL_ORG);
        controller.jobStatusNotification();

        soccController.showDeploymentFlow = true;
        soccController.deploymentFlowOperations();

        Test.stopTest();
    }

    @IsTest static void scratchOrgOpen(){
        //Use the PageReference Apex class to instantiate a page
        PageReference pageRef = Page.ScratchOrgOpen;

        //In this case, the Visualforce page named 'DXOperation' is the starting point of this test method.
        Test.setCurrentPage(pageRef);

        Org__c orgScratch = [SELECT Id, Environment__c FROM Org__c WHERE Name =: 'Scratch Org 1'];

        Copado_Notification__c cn = new Copado_Notification__c();
        cn.Type__c = CopadoNotificationHelper.DX_OPEN_ORG;
        cn.OwnerId = UserInfo.getUserId();
        cn.isFinished__c = false;
        cn.ParentId__c = orgScratch.Id;
        cn.Matching_Key__c = 'testmatching';
        insert cn;

        pageRef.getParameters().put('id',orgScratch.Id);

        //Instantiate and construct the controller class of DX Operation page.
        ScratchOrgOpen sooController = new ScratchOrgOpen();
        sooController.soId = orgScratch.Id;

        System.assertEquals(null,sooController.copadoJobFinished);

        //Open scratch org
        Test.startTest();
        MockHttpResponseGenerator fakeResponseCopadoId = new MockHttpResponseGenerator(200,'Complete','{"test":"123456789012345678"}',null);
        Test.setMock(HttpCalloutMock.class, fakeResponseCopadoId);
        sooController.rScratchOrgJob();
        Test.stopTest();
    }

    // Those method are never used, because they are overwritten.
    @IsTest static void overWrittenMethods(){
        Test.startTest();
        ScratchOrgWizardPageBase scowpb = new ScratchOrgWizardPageBase();
        ScratchOrgWizardComponentBase controller = scowpb.getChildComponentController();
        scowpb.getThis();

        scowpb.setComponentControllerMap('ScratchOrgComponent', controller);
        Map<String, ScratchOrgWizardComponentBase> testScowpb = scowpb.getComponentControllerMap();
        Test.stopTest();
    }
}