objects/Deployment_Flow__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, all Branch Management features will be enabled in the Deployment Flow.</description>
        <inlineHelpText>If checked, all Branch Management features will be enabled in the Deployment Flow.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Git_Repository__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>Git_Repository__c</referenceTo>
        <relationshipName>Deployment_Flows</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Main_Branch__c</fullName>
        <description>Main branch of the selected Git Repository (e.g. master).</description>
        <inlineHelpText>Main branch of the selected Git Repository (e.g. master).</inlineHelpText>
        <label>Main Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deployment_Flow_Step__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <inlineHelpText>Git branch linked to the source environment.</inlineHelpText>
        <label>Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deployment_Flow__c</fullName>
        <label>Pipeline</label>
        <referenceTo>Deployment_Flow__c</referenceTo>
        <relationshipLabel>Pipeline Connections</relationshipLabel>
        <relationshipName>Deployment_Flow_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Destination_Branch__c</fullName>
        <description>Value updated automatically by Copado. This is defined in the Deployment Flow Step of the Destination Environment.</description>
        <inlineHelpText>Value updated automatically by Copado. This is defined in the Deployment Flow Step of the Destination Environment.</inlineHelpText>
        <label>Destination Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Destination_Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Destination Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipName>Deployment_Flow_Steps1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Environment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Source Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipName>Deployment_Flow_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pipeline Connection</label>
    <nameField>
        <displayFormat>DFS-{000000}</displayFormat>
        <label>Pipeline Connection Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pipeline Connections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Environment__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Production/Developer</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch Org</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Git_Backup__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <description>Branch of the selected Git Repository (e.g. master). Snapshots and Commits done in the Git Snapshot will affect the specified branch.</description>
        <inlineHelpText>Git branch related to the Org. Be aware that branch names are case sensitive.</inlineHelpText>
        <label>Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Git_Repository__c</fullName>
        <description>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>Git_Repository__c</referenceTo>
        <relationshipLabel>Git Snapshots</relationshipLabel>
        <relationshipName>Git_Backups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <description>A validated Org Credential used to retrieve the metadata that will be committed to the specified Branch in the Git Snapshot.</description>
        <inlineHelpText>A validated Org Credential used to retrieve the metadata that will be committed to the specified Branch in the Git Snapshot.</inlineHelpText>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Git Snapshots</relationshipLabel>
        <relationshipName>Git_Backups</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Git Snapshot</label>
    <nameField>
        <label>Git Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Git_Repository__c.object
<CustomObject>
    <description>Connection to a git repository like github.com or bitbuckets.org</description>
    <label>Git Repository</label>
    <nameField>
        <label>Git Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</description>
        <inlineHelpText>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Org Credentials</relationshipLabel>
        <relationshipName>Org_Credentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/DeploymentFlowStepTriggerHelper.cls
public class DeploymentFlowStepTriggerHelper {
    public static Integer existingFlows = 0;
    public static Integer existingSteps = 0;
    public static Integer newStepCount = 0;
    public static boolean isFeatureEnabled = false;
    private static LicenseManagerController lmc = new LicenseManagerController();

    public class ApplicationException extends Exception {}

    public static void prepareData(){
        isFeatureEnabled = FeatureHelper.isFeatureEnabled('Branch Management');

        Set<Id> idset = new Set<Id>();
        for(SObject so : Trigger.new){
            if(so.Id!=null)idset.add(so.Id);
        }

        existingSteps = [select count() from Deployment_Flow_Step__c where
        Deployment_Flow__r.Active__c=true and
        (NOT Source_Environment__r.Type__c LIKE 'Scratch Org%') AND// MY: Added to exclude scratch orgs from used CBM licenses
        Deployment_Flow__r.Main_Branch__c!=null and
        Deployment_Flow__r.Git_Repository__c!=null and
        Branch__c!=null and (NOT(Id in :idset)) ];

        newStepCount = 0;
        for(SObject so : Trigger.new){
            Deployment_Flow_Step__c dfs = (Deployment_Flow_Step__c)so;
            if(dfs.Source_Environment__c != null && (String.isNotBlank(dfs.Source_Environment__r.Type__c) && !dfs.Source_Environment__r.Type__c.startsWithIgnoreCase('Scratch Org'))) { // MY: Added to exclude scratch orgs from used CBM licenses
                if (isValidFlowStep(dfs))newStepCount++;
            }
        }
        Integer totalCount = existingSteps + newStepCount;
        Integer allowedCount = lmc.cbmBranchesAvailable;
        for(SObject so : Trigger.new){
            Deployment_Flow_Step__c dfs = (Deployment_Flow_Step__c)so;
            if(isValidFlowStep(dfs)){
                if(!isFeatureEnabled){
                    dfs.addError(Label.BRANCH_MGMT_NOT_ENABLED);
                }
                else if(totalCount > allowedCount){
                    dfs.addError(Label.BRANCH_MGMT_LICENSE_EXCEEDED);
                }
            }
        }
    }
    public static boolean isValidFlowStep(Deployment_Flow_Step__c dfs){
        return (String.isNotBlank(dfs.branch__c) && dfs.Deployment_Flow__r.Active__c == true);
    }

    public static void firePossibleFlowValidations(List<Deployment_Flow_Step__c> Ldfs) {

        System.Debug('Enter firePossibleFlowValidations');

        Map<Id,Deployment_Flow__c> MdfIds = new Map<Id,Deployment_Flow__c>();

        for (Deployment_Flow_Step__c dfs: Ldfs) {
            Deployment_Flow__c df = new Deployment_Flow__c();
            df.Id = dfs.Deployment_Flow__c;
            MdfIds.put(df.Id,df);
        }

        try {
            update MdfIds.values();
        }
        catch (Exception e) {
            String mess = e.getMessage();
            String validationException = 'FIELD_CUSTOM_VALIDATION_EXCEPTION';
            mess = mess.substring(mess.indexOf(validationException)+validationException.length()+2, mess.length()-1);
            System.Debug('Exception mess = ' + mess);
            throw new applicationException(mess);
        }
    }

    public static void populateFlowStepDestinationBranch(List<Deployment_Flow_Step__c> deploymentFlowSteps, Map<Id, Deployment_Flow_Step__c> oldMap) {
        Set<Id> destinationEnvironmentIds = new Set<Id>();
        for(Deployment_Flow_Step__c thisStep : deploymentFlowSteps) {
            if(Trigger.isUpdate) {
                Deployment_Flow_Step__c oldStep = oldMap.get(thisStep.Id);
                if(thisStep.Destination_Environment__c != oldStep.Destination_Environment__c) {
                    if(thisStep.Destination_Environment__c != null) {
                        destinationEnvironmentIds.add(thisStep.Destination_Environment__c);
                    } else {
                        thisStep.Destination_Branch__c = null;
                    }
                }
            } else {
                if(thisStep.Destination_Environment__c != null) {
                    destinationEnvironmentIds.add(thisStep.Destination_Environment__c);
                }
            }
        }

        if(destinationEnvironmentIds.isEmpty()) {
            return;
        }

        List<Git_Backup__c> gitSnapshots = [SELECT Branch__c, Org__r.Environment__c FROM Git_Backup__c
        WHERE Org__r.Environment__c IN :destinationEnvironmentIds];

        if(gitSnapshots.isEmpty()) {
            return;
        }

        Map<Id, Git_Backup__c> gitSnapshotsByEnvironmentMap = new Map<Id, Git_Backup__c>();
        for(Git_Backup__c thisSnapshot : gitSnapshots) {
            if(!gitSnapshotsByEnvironmentMap.containsKey(thisSnapshot.Org__r.Environment__c)) {
                gitSnapshotsByEnvironmentMap.put(thisSnapshot.Org__r.Environment__c, thisSnapshot);
            }
        }
        for(Deployment_Flow_Step__c thisStep : deploymentFlowSteps) {
            Git_Backup__c thisSnapshot = gitSnapshotsByEnvironmentMap.get(thisStep.Destination_Environment__c);
            if(thisSnapshot != null) {
                thisStep.Destination_Branch__c = thisSnapshot.Branch__c;
            }
        }
    }
}