objects/Deployment_Flow__c.object
<CustomObject>
    <fields>
        <fullName>Git_Repository__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>Git_Repository__c</referenceTo>
        <relationshipName>Deployment_Flows</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pipeline</label>
    <nameField>
        <label>Pipeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Git_Repository__c.object
<CustomObject>
    <description>Connection to a git repository like github.com or bitbuckets.org</description>
    <label>Git Repository</label>
    <nameField>
        <label>Git Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <fields>
        <fullName>Developer_Hub_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Developer Hub Org</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Org__c.is_Developer_Hub_Org__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Org Credentials</relationshipLabel>
        <relationshipName>Org_Credentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org_Type__c</fullName>
        <label>Org Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Production/Developer</fullName>
                    <default>true</default>
                    <label>Production/Developer</label>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch Org</fullName>
                </value>
                <value>
                    <fullName>Scratch Org - Test only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Scratch_Org_Expiration_Date__c</fullName>
        <label>Scratch Org Expiration Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Scratch_Org_Status__c</fullName>
        <label>Scratch Org Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Missing</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <fields>
        <fullName>Deployment_Flow__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If working with Copado Change Management, the Project must be linked to a Pipeline.</inlineHelpText>
        <label>Pipeline</label>
        <referenceTo>Deployment_Flow__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Release__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Releases</relationshipLabel>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Test_Run__c.object
<CustomObject>
    <description>The execution of the test script.</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Test_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Test_Script__c</fullName>
        <label>Test Script</label>
        <referenceTo>Test_Script__c</referenceTo>
        <relationshipName>Test_Executions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipName>Test_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Run</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Test Run Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Runs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Test_Script__c.object
<CustomObject>
    <description>The template test script.</description>
    <fields>
        <fullName>Org__c</fullName>
        <label>Org</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>User_Story__r.Project__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipLabel>Test Scripts (User Story)</relationshipLabel>
        <relationshipName>Test_Scripts_UserStory</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{00000}</displayFormat>
        <label>Test Script Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</description>
        <inlineHelpText>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</inlineHelpText>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>User Stories (Org Credential)</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project where the User Story belongs.</description>
        <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product version or release where this User Story will be released.</description>
        <inlineHelpText>Product version or release where this User Story will be released.</inlineHelpText>
        <label>Release</label>
        <referenceTo>Release__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DynamicScratchOrgController.cls
/**
 * Created by mertyalti on 01/02/2018.
 */

public with sharing class DynamicScratchOrgController extends ScratchOrgWizardPageBase {
    public Test_Run__c testRun { get; set; }
    private Id stdObjectId;
    private String sourceBranch;
    public String initialPageMessage { get; set; }
    public Boolean showInitialPageMessage { get; set; }
    public Boolean showComponent { get; set; }

    public DynamicScratchOrgController(ApexPages.StandardController std) {
        showComponent = true;
        showInitialPageMessage = true;
        stdObjectId = std.getId();
        SObjectType parentObject = stdObjectId.getSobjectType();
        if (parentObject == SObjectType.Test_Run__c.getSObjectType()) {
            testRunOperation();
        }
    }
    private void testRunOperation() {
        try {
            testRun = [
                SELECT
                    Name,
                    Test_Script__r.User_Story__r.Org_Credential__r.Org_Type__c,
                    Test_Script__r.User_Story__r.Org_Credential__r.Developer_Hub_Org__c,
                    Test_Script__r.User_Story__r.Org_Credential__c,
                    Test_Script__r.User_Story__r.Name,
                    Test_Script__r.User_Story__r.Project__c,
                    Test_Script__r.User_Story__r.Project__r.Deployment_Flow__c,
                    Test_Script__r.User_Story__r.Project__r.Deployment_Flow__r.Git_Repository__c,
                    Test_Script__r.User_Story__r.Release__c,
                    Test_Script__r.User_Story__r.Release__r.Project__c,
                    Test_Script__r.User_Story__r.Release__r.Project__r.Deployment_Flow__c,
                    Test_Script__r.User_Story__r.Release__r.Project__r.Deployment_Flow__r.Git_Repository__c
                FROM Test_Run__c
                WHERE Id = :stdObjectId
                WITH SECURITY_ENFORCED
            ];
        } catch (System.QueryException ex) {
            addPageMessage(ApexPages.Severity.ERROR, Test_Run__c.SObjectType.getDescribe().getLabel() + ': ' + Label.Insufficient_Access_Rights);
            return;
        }

        if (
            testRun != null &&
            testRun.Test_Script__c != null &&
            testRun.Test_Script__r.User_Story__c != null &&
            testRun.Test_Script__r.User_Story__r.Org_Credential__c != null &&
            testRun.Test_Script__r.User_Story__r.Org_Credential__r.Org_Type__c == 'Scratch Org' &&
            testRun.Test_Script__r.User_Story__r.Org_Credential__r.Developer_Hub_Org__c != null
        ) {
            Id orgId = testRun.Test_Script__r.User_Story__r.Org_Credential__c;
            Org__c usOrg;
            try {
                usOrg = [
                    SELECT Org_Type__c, Scratch_Org_Expiration_Date__c, Scratch_Org_Status__c, Developer_Hub_Org__c
                    FROM Org__c
                    WHERE Id = :orgId
                    WITH SECURITY_ENFORCED
                ];
            } catch (System.QueryException ex) {
                addPageMessage(ApexPages.Severity.ERROR, Org__c.SObjectType.getDescribe().getLabel() + ': ' + Label.Insufficient_Access_Rights);
                return;
            }
            setDevHubOrgId(usOrg.Developer_Hub_Org__c);
            sourceBranch = SfdxAPIHelper.DX_PROJECT_BRANCH + String.valueOf(testRun.Test_Script__r.User_Story__r.Org_Credential__c).substring(3, 15);
            initialPageMessage = 'Test Scratch org will be created out of ' + sourceBranch;
            try {
                Attachment attDefinition = getOrgAttachment(orgId, SfdxAPIHelper.DX_DEFINITION_FILE);
                Attachment attProject = getOrgAttachment(orgId, SfdxAPIHelper.DX_PROJECT_FILE);
                ScratchOrgDefinition orgTemplate = (ScratchOrgDefinition) JSON.deserialize(attDefinition.Body.toString(), ScratchOrgDefinition.class);
                orgTemplate.setOrgName(testRun.Name + ' Scratch Org');
                orgTemplate.setUsername('');
                setOrgTemplate(orgTemplate);
                String projectJson = attProject.Body.toString();
                projectJson = projectJson.replaceAll('"package":', '"packageName":');
                projectJson = projectJson.replaceAll('"default":', '"defaultArtifact":');
                DXProject artifactProject = (DXProject) JSON.deserialize(projectJson, DXProject.class);
                setArtifactProject(artifactProject);
            } catch (Exception ex) {
                addPageMessage(ApexPages.Severity.ERROR, 'Error during test run operations with message: ' + ex.getMessage());
            }
        } else {
            showComponent = false;
            addPageMessage(ApexPages.Severity.ERROR, 'No org credentials found or missing configuration.');
        }
    }

    private Attachment getOrgAttachment(Id ParentId, String attName) {
        //if (hasAccessTo(parentId.getSobjectType())) { probably not needed
            try {
                return [
                    SELECT Body, ParentId, Name
                    FROM Attachment
                    WHERE ParentId = :ParentId AND Name = :attName
                    WITH SECURITY_ENFORCED
                    ORDER BY CreatedDate DESC
                    LIMIT 1
                ];
            } catch (System.QueryException ex) {
                addPageMessage(ApexPages.Severity.ERROR, Attachment.SObjectType.getDescribe().getLabel() + ': ' + ex.getMessage());
                return null;
            }
        //}
        //return null;
    }

    public PageReference loadReviewData() {
        ScratchOrgDefinition orgTemplate = getOrgTemplate();
        DXProject artifactProject = getArtifactProject();
        if (orgTemplate != null && artifactProject != null) {
            ScratchOrgCompletionController completionController = ((ScratchOrgCompletionController) getComponentController('ScratchOrgCompletion'));
            completionController.orgDefinition = orgTemplate;
            completionController.artifactProject = artifactProject;
            completionController.artifactDirectories = new List<ProjectArtifact>();
            for (ProjectArtifact art : artifactProject.getPackageDirectories()) {
                Boolean defaultArtifact = art.getDefaultArtifact() != null ? art.getDefaultArtifact() : art.getPath() == 'force-app';
                completionController.artifactDirectories.add(new ProjectArtifact(art.getPath(), defaultArtifact));
            }
            completionController.parentId = stdObjectId;
            completionController.setDevHubOrgId(getDevHubOrgId());
            completionController.showPermissionsPanel = false;
            completionController.sourceBranch = sourceBranch;
            completionController.showSetup = false;
        }
        return null;
    }

    public PageReference jobStatusNotification() {
        Map<String, String> pageParameters = ApexPages.currentPage().getParameters();
        Boolean jobFinished = pageParameters.get('jobFinished') == 'true';

        if (jobFinished) {
            Boolean jobSuccess = pageParameters.get('jobSuccess') == 'true';
            if (jobSuccess) {
                String jobType = pageParameters.get('jobType');
                if (String.isNotBlank(jobType)) {
                    addPageMessage(ApexPages.Severity.CONFIRM, Label.Scratch_Org_Created_Success);
                    PageReference pRef = Page.DXTestOrgIntermediary;
                    pRef.getParameters().put('id', testRun.Id);
                    pRef.setRedirect(true);
                    return pRef;
                }
            } else {
                String jobMessage = pageParameters.get('jobMessage');
                if (String.isNotBlank(jobMessage)) {
                    addPageMessage(ApexPages.Severity.ERROR, jobMessage);
                }
            }
        }

        return null;
    }

    /**
     * @description checks if the user has read access to a Salesforce Object and displays an error message otherwise.
     *
     * @param thisObjectType is the SObject type being evaluated.
     *
     * @return a flag indicating if a user has access to the given SObject type or not.
     */
    private Boolean hasAccessTo(SObjectType thisObjectType) {
        Boolean hasAccess = thisObjectType.getDescribe().isAccessible() && thisObjectType.getDescribe().isQueryable();
        if (!hasAccess) {
            addPageMessage(ApexPages.Severity.WARNING, thisObjectType.getDescribe().getLabel() + ': ' + Label.Insufficient_Access_Rights);
        }
        return hasAccess;
    }

    /**
     * @description a utility method for displaying messages on the parent page.
     *
     * @param severity is the ApexPages.Severity enum value for the type of message.
     * @param message is the actual message to be shown to the user.
     */
    private void addPageMessage(ApexPages.Severity severity, String message) {
        ApexPages.addMessage(new ApexPages.Message(severity, message));
    }
}