objects/Environment__c.object
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Git_Org_Commit__c.object
<CustomObject>
    <description>This object stores the individual commits to a Git repository executed by Copado Deployer.</description>
    <label>Snapshot Commit</label>
    <nameField>
        <displayFormat>Cmt-{0000}</displayFormat>
        <label>Commit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snapshot Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</description>
        <inlineHelpText>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Org Credentials</relationshipLabel>
        <relationshipName>Org_Credentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Snapshot_Difference__c.object
<CustomObject>
    <fields>
        <fullName>Destination_Git_Commit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Destination Git Commit</label>
        <referenceTo>Git_Org_Commit__c</referenceTo>
        <relationshipLabel>Snapshot Differences (Destination Git Commit)</relationshipLabel>
        <relationshipName>Snapshot_Differences1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Destination_Option__c</fullName>
        <label>Destination Option</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Git Commit</fullName>
                </value>
                <value>
                    <fullName>Salesforce Org</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Destination_Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Destination Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Snapshot Differences (Destination Org Credential)</relationshipLabel>
        <relationshipName>Snapshot_Differences1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Run__c</fullName>
        <label>Last Run</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Partial_Selection__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>To calculate the differences only of selected files, select this checkbox.</inlineHelpText>
        <label>Partial Selection</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source_Git_Commit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Git Commit</label>
        <referenceTo>Git_Org_Commit__c</referenceTo>
        <relationshipLabel>Snapshot Differences</relationshipLabel>
        <relationshipName>Snapshot_Differences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Option__c</fullName>
        <label>Source Option</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Git Commit</fullName>
                </value>
                <value>
                    <fullName>Salesforce Org</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Snapshot Differences</relationshipLabel>
        <relationshipName>Snapshot_Differences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Snapshot Difference</label>
    <nameField>
        <label>Snapshot Difference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Snapshot Differences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</description>
        <inlineHelpText>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</description>
        <inlineHelpText>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</inlineHelpText>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>User Stories (Org Credential)</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story_Task__c.object
<CustomObject>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipLabel>User Story Tasks</relationshipLabel>
        <relationshipName>User_Story_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Story Task</label>
    <nameField>
        <displayFormat>UST-{0000000}</displayFormat>
        <label>User Story Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Story Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/snapshotDifferenceExtension.cls
public with sharing class snapshotDifferenceExtension {
    //public boolean disableRunDeepDiff {get;set;}
    //public boolean renderDiffResults {get;set;}
    public Boolean isEdit { get; set; }
    public Settings settings { get; set; }
    public Snapshot_Difference__c snapshot { get; set; }
    public ApexPages.StandardController controller { get; set; }
    public String keyPrefix { get; set; }
    public Boolean isSnapshotEnabled { get; set; }
    public Boolean isShareable { get; set; }
    public Boolean showError { get; set; }
    public Boolean showOptions { get; set; }
    public Id usId { get; set; }
    public User_Story_Task__c us4Lookup {
        get {
            if(null == us4Lookup) {
                us4Lookup  = new User_Story_Task__c();
            }
            return us4Lookup ;
        }
        set;
    }
    private final String SNAPSHOT_DIFFERENCE = 'Snapshot Difference';
    private final String GIT_COMMIT = 'Git Commit';
    private final String SALESFORCE_ORG = 'Salesforce Org';

    public static final String[] SNAPSHOT_FIELDS = new String[]{
            'Id', 'Name', 'Last_Run__c', 'Source_Option__c', 'Destination_Option__c', 'Source_Git_Commit__c', 'Destination_Git_Commit__c', 'Source_Org_Credential__c', 'Destination_Org_Credential__c'
    };

    public snapshotDifferenceExtension(ApexPages.StandardController stdController) {
        showOptions = true;
        showError = false;
        isLicenseEnabled();
        settings = new Settings();

        controller = stdController;
        if(!Test.isRunningTest()) {
            stdController.addFields(SNAPSHOT_FIELDS); stdController.addFields(new List<String>{
                    'source_org_credential__r.environment__c'
            });
        }
        this.snapshot = (Snapshot_Difference__c) stdController.getRecord();
        DescribeSObjectResult dsr = Git_Org_Commit__c.SObjectType.getDescribe();
        keyPrefix = dsr.getKeyPrefix();
        //renderDiffResults = false;
        //disableRunDeepDiff = true;
        isEdit = true;
        if(this.snapshot == null) {
            this.snapshot = new Snapshot_Difference__c();
            //disableRunDeepDiff = true;
        }
        //calculate last run based on lastmodified date of index.json
        if(!String.isBlank(this.snapshot.Id)) {
            if(Schema.SObjectType.Attachment.isQueryable() && Schema.SObjectType.Attachment.isAccessible()) {
                List<Attachment> attList = [SELECT LastModifiedDate FROM Attachment WHERE ParentId = :this.snapshot.Id AND Name = 'index.json' ORDER BY LastModifiedDate DESC LIMIT 1];
                if(attList.size() == 1) {
                    this.snapshot.Last_Run__c = attList.get(0).LastModifiedDate;
                }
            } else {
                //TODO add global method for insufficient access error when it is back-promoted
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, Schema.SObjectType.Attachment.getName() + ': ' + Label.Insufficient_Access_Rights));
            }
        }

        /*if(snapshot.Id != null && snapshot.Last_Run__c != null) {
            this.renderDiffResults = true;
            disableRunDeepDiff = false;
        }*/
        if(snapshot.Id != null) {
            isEdit = false;
        }
        //evaludateDisableRunDiff();

        isSnapshotEnabled = true;
        Boolean isLicensesExceeded = LicenseHelper.isLicensesExceeded();
        if(!FeatureHelper.isFeatureEnabled(SNAPSHOT_DIFFERENCE) || isLicensesExceeded) {
            if(isLicensesExceeded) {
                ApexPages.addMessage(new Apexpages.Message(Apexpages.Severity.ERROR, Label.LICENSES_EXCEEDED));
            } else {
                ApexPages.addMessage(new Apexpages.Message(Apexpages.Severity.WARNING, Label.FEATURE_NOT_SUPPORTED + ' ' + SNAPSHOT_DIFFERENCE));
            }
            isSnapshotEnabled = false;
        }
        System.debug('*** feature enabled: ' + isSnapshotEnabled);
        Map<String, Schema.SObjectType> tokens = Schema.getGlobalDescribe();
        isShareable = tokens.containsKey('Snapshot_Difference__Share');
    }
    /*public void evaludateDisableRunDiff(){
        if(snapshot.Source_Option__c==null || snapshot.Destination_Option__c==null){
            disableRunDeepDiff = true;
            return;
        }
        if(snapshot.Source_Option__c=='Git Commit' && snapshot.Source_Git_Commit__c==null)disableRunDeepDiff = true;
        if(snapshot.Destination_Option__c=='Git Commit' && snapshot.Destination_Git_Commit__c==null)disableRunDeepDiff = true;
        if(snapshot.Source_Option__c=='Salesforce Org' && snapshot.Source_Org_Credential__c==null)disableRunDeepDiff = true;
        if(snapshot.Destination_Option__c=='Salesforce Org' && snapshot.Destination_Org_Credential__c==null)disableRunDeepDiff = true;
        disableRunDeepDiff = false;
    }*/
    public void doRerender() {
        //evaludateDisableRunDiff();
        if(snapshot.Destination_Option__c == null) {
            snapshot.Destination_Org_Credential__c = null;
            snapshot.Destination_Git_Commit__c = null;
        }
        if(snapshot.Destination_Option__c == GIT_COMMIT) {
            snapshot.Destination_Org_Credential__c = null;
        }
        if(snapshot.Destination_Option__c == SALESFORCE_ORG) {
            snapshot.Destination_Git_Commit__c = null;
        }

        if(snapshot.Source_Option__c == null) {
            snapshot.Source_Org_Credential__c = null;
            snapshot.Source_Git_Commit__c = null;
        }
        if(snapshot.Source_Option__c == GIT_COMMIT) {
            snapshot.Source_Org_Credential__c = null;
            snapshot.Partial_Selection__c = false;
        }
        if(snapshot.Source_Option__c == SALESFORCE_ORG) {
            snapshot.Source_Git_Commit__c = null;
            snapshot.Partial_Selection__c = false;
        }
    }
    public void edit() {
        isEdit = true;
    }
    public void isLicenseEnabled() {
        if(!LicenseHelper.actionIsLicenseEnabled('viewEditSnapshotDifferences')) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, Label.CCM_License_Restriction));
            showError = true;
            showOptions = false;
        }
        return;
    }

    public PageReference cancel() {
        return controller.cancel();
    }
    public PageReference save() {
        String errorMsg = Label.Source_Destination_validation_for_commit;
        if(snapshot.Source_Option__c == null || snapshot.Destination_Option__c == null) {
            snapshot.addError(errorMsg);
            return null;
        }
        if((snapshot.Source_Option__c == SALESFORCE_ORG && snapshot.Source_Org_Credential__c == null)
                || (snapshot.Destination_Option__c == SALESFORCE_ORG && snapshot.Destination_Org_Credential__c == null)) {
            snapshot.addError(errorMsg);
            return null;
        }
        if((snapshot.Source_Option__c == GIT_COMMIT && snapshot.Source_Git_Commit__c == null)
                || (snapshot.Destination_Option__c == GIT_COMMIT && snapshot.Destination_Git_Commit__c == null)) {
            snapshot.addError(errorMsg);
            return null;
        }
        PageReference pref = controller.save();

        return pref;
    }

    public void checkEnvironment() {
        showError = false;
        usId = us4Lookup.User_Story__c;
        String errorMsg = Label.Environment_selected_US_same_Environment;
        Id usOrgId;
        if(Schema.SObjectType.User_Story__c.isQueryable() && Schema.SObjectType.User_Story__c.isAccessible()) {
            usOrgId = [SELECT Org_Credential__c,Environment__c FROM User_Story__c WHERE Id = :us4Lookup.User_Story__c].Environment__c;
        } else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, Schema.SObjectType.User_Story__c.getName() + ': ' + Label.Insufficient_Access_Rights));
        }
        if(this.snapshot.Source_Org_Credential__c != null && this.snapshot.Source_Org_Credential__r.Environment__c != usOrgId) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, errorMsg));
            showError = true;
        }
    }
}