objects/Metadata_Group__c.object
<CustomObject>
    <label>Metadata Group</label>
    <nameField>
        <label>Metadata Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metadata Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Metadata_Group_Item__c.object
<CustomObject>
    <fields>
        <fullName>Metadata_Group__c</fullName>
        <description>The parent metadata group this item belongs to</description>
        <inlineHelpText>The parent metadata group this item belongs to</inlineHelpText>
        <label>Parent Group</label>
        <referenceTo>Metadata_Group__c</referenceTo>
        <relationshipLabel>Metadata Items</relationshipLabel>
        <relationshipName>Metadata_Group_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <description>Match &apos;All&apos; metadata of this type, or only metadata whose name matches a pattern?</description>
        <inlineHelpText>Match &apos;All&apos; metadata of this type, or only metadata whose name matches a pattern?</inlineHelpText>
        <label>Metadata Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Operator</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of metadata</description>
        <inlineHelpText>The type of metadata</inlineHelpText>
        <label>Metadata Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Metadata_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>Match only metadata whose name matches this value (ignored if Metadata Name = &apos;All&apos; is selected)</description>
        <inlineHelpText>Match only metadata whose name matches this value (ignored if Metadata Name = &apos;All&apos; is selected)</inlineHelpText>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Metadata Item</label>
    <nameField>
        <displayFormat>MGI-{00000000}</displayFormat>
        <label>Metadata Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metadata Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CCD_CreateMetadataGroupExtension.cls
public with sharing class CCD_CreateMetadataGroupExtension {
    public Metadata_Group__c thisMetadataGroup { get; set; }
    public static Metadata_Group_Item__c groupItemFilter { get; set; }
    public String selectedMetadataItemName { get; set; }
    public List<Metadata_Group_Item__c> groupItems { get; set; }
    public List<SelectOption> itemTypeOptions {
        get {
            if(itemTypeOptions == null) {
                itemTypeOptions = new List<SelectOption>();
                List<Schema.PicklistEntry> picklistValues = Metadata_Group_Item__c.Type__c.getDescribe().getPicklistValues();
                for(PicklistEntry thisValue : picklistValues) {
                    SelectOption thisOption = new SelectOption(thisValue.getValue(), thisValue.getLabel());
                    itemTypeOptions.add(thisOption);
                }
            }
            return itemTypeOptions;
        }
        private set;
    }
    public List<SelectOption> itemOperatorOptions {
        get {
            if(itemOperatorOptions == null) {
                itemOperatorOptions = new List<SelectOption>();
                List<Schema.PicklistEntry> picklistValues = Metadata_Group_Item__c.Operator__c.getDescribe().getPicklistValues();
                for(PicklistEntry thisValue : picklistValues) {
                    SelectOption thisOption = new SelectOption(thisValue.getValue(), thisValue.getLabel());
                    itemOperatorOptions.add(thisOption);
                }
            }
            return itemOperatorOptions;
        }
        private set;
    }

    static {
        groupItemFilter = new Metadata_Group_Item__c();
    }

    public CCD_CreateMetadataGroupExtension(ApexPages.StandardController thisStdController) {
        thisMetadataGroup = (Metadata_Group__c) thisStdController.getRecord();

        if(thisMetadataGroup.Id != null) {
            getMetadataGroupItems();
        } else {
            groupItems = new List<Metadata_Group_Item__c>();
        }
    }

    private void getMetadataGroupItems() {
        groupItems = [SELECT Type__c, Operator__c, Value__c FROM Metadata_Group_Item__c
                      WHERE Metadata_Group__c = :thisMetadataGroup.Id];
    }

    public void addGroupItem() {
        Metadata_Group_Item__c thisItem = new Metadata_Group_Item__c();
        thisItem.Type__c = groupItemFilter.Type__c;

        if(selectedMetadataItemName == Label.ALL) {
            thisItem.Operator__c = Label.ALL;
            thisItem.Value__c = '*';
        } else {
            thisItem.Operator__c = groupItemFilter.Operator__c;
            thisItem.Value__c = groupItemFilter.Value__c;
        }

        groupItems.add(thisItem);
    }

    public PageReference save() {
        ApexPages.getMessages().clear();

        try {
            Utilities.Secure_DML(thisMetadataGroup, Utilities.DML_Action.UPS, SObjectType.Metadata_Group__c);

            for(Metadata_Group_Item__c thisItem : groupItems) {
                if(thisItem.Id == null) {
                    thisItem.Metadata_Group__c = thisMetadataGroup.Id;
                }
            }

            Utilities.Secure_DML(groupItems, Utilities.DML_Action.UPS, SObjectType.Metadata_Group_Item__c);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, Label.SAVE_SUCCESS));
        } catch(Exception ex) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
        }

        return null;
    }
}