objects/Org__c.object
<CustomObject>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Snapshot_Difference__c.object
<CustomObject>
    <fields>
        <fullName>Destination_Option__c</fullName>
        <label>Destination Option</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Git Commit</fullName>
                </value>
                <value>
                    <fullName>Salesforce Org</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Destination_Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Destination Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Snapshot Differences (Destination Org Credential)</relationshipLabel>
        <relationshipName>Snapshot_Differences1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Option__c</fullName>
        <label>Source Option</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Git Commit</fullName>
                </value>
                <value>
                    <fullName>Salesforce Org</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Snapshot Differences</relationshipLabel>
        <relationshipName>Snapshot_Differences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Snapshot Difference</label>
    <nameField>
        <label>Snapshot Difference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Snapshot Differences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestSnapshotDifferenceExtension.cls
@isTest
private class TestSnapshotDifferenceExtension {
    @testSetup static void setupData() {
        TestUtilities.setTestSettingsEE();
    }
    @testSetup static void setupDataDML() {
        testMethodUtilities.upsertOrgwideSettings();
    }
    @isTest
    static void test() {

        Org__c testOrg1 = CMTestMethodUtilities.createOrg('MyOrg1', 'Production', 'SFDC_OrgId', null, null, system.now(), null);
        insert testOrg1;

        Org__c testOrg2 = CMTestMethodUtilities.createOrg('MyOrg2', 'Production', 'SFDC_OrgId2', null, null, system.now(), null);
        insert testOrg2;
        Snapshot_Difference__c sn = new Snapshot_Difference__c(Source_Org_Credential__c = testOrg1.Id,
                Destination_Org_Credential__c = testOrg2.Id,
                Name = 'test',
                Source_Option__c = 'Salesforce Org',
                Destination_Option__c = 'Salesforce Org');
        snapshotDifferenceExtension ext = new snapshotDifferenceExtension(new ApexPages.StandardController(sn));
        ext.cancel();
        insert sn;
        ext = new snapshotDifferenceExtension(new ApexPages.StandardController(sn));
        ext.doRerender();
        ext.edit();
        ext.cancel();
        update sn;
        delete sn;
        undelete sn;

        sn.Source_Option__c = 'Git Commit';
        update sn;
        ext.doRerender();

        sn.Destination_Option__c = 'Git Commit';
        update sn;
        ext.doRerender();
        System.assertEquals(null, sn.Destination_Org_Credential__c);

        sn.Source_Option__c = 'Salesforce Org';
        update sn;
        ext.doRerender();

        sn.Source_Option__c = 'Git Commit';
        sn.Destination_Option__c = 'Salesforce Org';
        update sn;
        ext.doRerender();
        System.assertEquals(null, sn.Source_Org_Credential__c);

        sn.Source_Option__c = null;
        sn.Destination_Option__c = null;
        update sn;
        ext.doRerender();

        sn.Source_Option__c = 'Salesforce Org';
        sn.Destination_Option__c = 'Salesforce Org';
        update sn;
        ext.doRerender();
        ext.save();
        User_Story__c testUserStory = CMTestMethodUtilities.createUserStory('test');
        insert testUserStory;
        ext.us4Lookup.user_story__c = testUserStory.id;
        ext.checkEnvironment();
    }
}