objects/Scheduled_Job__c.object
<CustomObject>
    <fields>
        <fullName>Run_as_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This User must have a Copado License assigned, created an Org credential for his Copado user and created API Key. This API Key will be used for the webhooks.</inlineHelpText>
        <label>Run as User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Scheduled_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Webhook_URL__c</fullName>
        <label>Webhook URL</label>
        <type>Url</type>
    </fields>
    <label>Scheduled Job</label>
    <nameField>
        <label>Scheduled Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduled Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WebhookSchedulable.cls
global with sharing class WebhookSchedulable implements Schedulable, Database.AllowsCallouts{
    private Id scheduledJobID;
    public WebhookSchedulable(Id jobId){
        this.scheduledJobID = jobId;
    }
    global void execute(SchedulableContext sc) {
        Scheduled_Job__c sched = [select Id, Name, Webhook_URL__c, Run_as_User__c from Scheduled_Job__c where Id = :this.scheduledJobID];
        String url = sched.Webhook_URL__c;
        if (String.isNotBlank(sched.Run_as_User__c)){
            String apikey = DeployAPI.getUserAPIKey();
            if(url.indexOf('api_key=')>0){
                url = url.left(url.indexOf('api_key=')-1);
            }
            if(url.indexOf('&') > -1 && url.indexOf('?') == -1){
                url = url.replace('&','?');
            }
            url += (url.indexOf('?') > -1 ? '&' : '?')+'api_key=' + apikey;
        }
        WebhookAPI.callGenericWebhookAtFuture(url, this.scheduledJobID);
    }
}